// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeatFlow.Infrastructure.Persistence;

#nullable disable

namespace SeatFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SeatFlowDbContext))]
    [Migration("20260725131348_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeatFlow.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AgeRestriction = 12,
                            Category = "Concert",
                            Description = "Demonstration event used for local development.",
                            Title = "SeatFlow Demo Concert"
                        });
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.EventSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BookingClosesAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("BookingOpensAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "StartsAtUtc");

                    b.HasIndex("HallId", "StartsAtUtc");

                    b.ToTable("event_sessions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            BookingClosesAtUtc = new DateTimeOffset(new DateTime(2026, 12, 15, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BookingOpensAtUtc = new DateTimeOffset(new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventId = new Guid("33333333-3333-3333-3333-333333333333"),
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsCancelled = false,
                            StartsAtUtc = new DateTimeOffset(new DateTime(2026, 12, 15, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.Hall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique();

                    b.ToTable("halls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Capacity = 12,
                            Name = "Main Hall",
                            VenueId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalReference")
                        .IsUnique();

                    b.HasIndex("ReservationId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventSessionId");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.ReservationSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionSeatId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SessionSeatId");

                    b.HasIndex("ReservationId", "SessionSeatId")
                        .IsUnique();

                    b.ToTable("reservation_seats", (string)null);
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("HallId")
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("RowLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "RowLabel", "Number")
                        .IsUnique();

                    b.ToTable("seats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Category = "Premium",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 1,
                            RowLabel = "A"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Category = "Premium",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 2,
                            RowLabel = "A"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Category = "Premium",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 3,
                            RowLabel = "A"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Category = "Premium",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 4,
                            RowLabel = "A"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000005"),
                            Category = "Premium",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 5,
                            RowLabel = "A"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000006"),
                            Category = "Premium",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 6,
                            RowLabel = "A"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000007"),
                            Category = "Standard",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 1,
                            RowLabel = "B"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000008"),
                            Category = "Standard",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 2,
                            RowLabel = "B"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000009"),
                            Category = "Standard",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 3,
                            RowLabel = "B"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000010"),
                            Category = "Standard",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 4,
                            RowLabel = "B"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000011"),
                            Category = "Standard",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 5,
                            RowLabel = "B"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000012"),
                            Category = "Standard",
                            HallId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Number = 6,
                            RowLabel = "B"
                        });
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.SessionSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventSessionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReservedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SeatId");

                    b.HasIndex("Status");

                    b.HasIndex("EventSessionId", "SeatId")
                        .IsUnique();

                    b.ToTable("session_seats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 80.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000001"),
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 80.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000002"),
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 80.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000003"),
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 80.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000004"),
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 80.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000005"),
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000006"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 80.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000006"),
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000007"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 50.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000007"),
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000008"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 50.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000008"),
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000009"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 50.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000009"),
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000010"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 50.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000010"),
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000011"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 50.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000011"),
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000012"),
                            EventSessionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Price = 50.00m,
                            SeatId = new Guid("50000000-0000-0000-0000-000000000012"),
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("venues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "100 Demo Avenue",
                            Description = "Demonstration venue for the SeatFlow API.",
                            Name = "SeatFlow Arena"
                        });
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.EventSession", b =>
                {
                    b.HasOne("SeatFlow.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeatFlow.Domain.Entities.Hall", null)
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.Hall", b =>
                {
                    b.HasOne("SeatFlow.Domain.Entities.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SeatFlow.Domain.Entities.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("SeatFlow.Domain.Entities.EventSession", null)
                        .WithMany()
                        .HasForeignKey("EventSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.ReservationSeat", b =>
                {
                    b.HasOne("SeatFlow.Domain.Entities.Reservation", null)
                        .WithMany("Seats")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeatFlow.Domain.Entities.SessionSeat", null)
                        .WithMany()
                        .HasForeignKey("SessionSeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.Seat", b =>
                {
                    b.HasOne("SeatFlow.Domain.Entities.Hall", null)
                        .WithMany()
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.SessionSeat", b =>
                {
                    b.HasOne("SeatFlow.Domain.Entities.EventSession", null)
                        .WithMany()
                        .HasForeignKey("EventSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeatFlow.Domain.Entities.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeatFlow.Domain.Entities.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeatFlow.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
